"""
SUBSCRIPTION PLAN ENGINE
5 Tiers from Free to Enterprise with 500+ features per plan.

Plans:
  Free       - $0/month     - Basic access, limited models, 100 karma/day
  Starter    - $9.99/month  - More models, 500 karma/day, basic analytics
  Pro        - $29.99/month - All models, unlimited karma, advanced analytics
  Ultimate   - $99.99/month - Priority support, custom models, API access
  Enterprise - $299.99/month - White-label, custom integrations, dedicated support

Lifetime Plans:
  Starter    - $299 one-time
  Pro        - $799 one-time
  Ultimate   - $1,999 one-time
  Enterprise - $4,999 one-time
"""

import os
import json
import time
from datetime import datetime

DATA_DIR = os.path.join(os.getcwd(), "data", "subscription")
os.makedirs(DATA_DIR, exist_ok=True)

SUB_FILE = os.path.join(DATA_DIR, "subscriptions.json")

# ============================================================
#  PLAN DEFINITIONS (500+ features per plan)
# ============================================================

PLAN_FEATURES = {
    "free": {
        "name": "Free",
        "price_monthly": 0,
        "price_lifetime": 0,
        "color": "dim",
        "icon": "--",
        "badge": "FREE",
        "features": [
            "Access to 10 base AI models",
            "Basic karma scoring",
            "Community leaderboard",
            "5 mining sessions/day",
            "Standard response speed",
            "Basic combo tracking",
            "Public project access",
            "Basic impact visualization",
            "Standard color themes",
            "Basic transaction history",
            "Community support forum",
            "Basic status dashboard",
            "Standard karma profile",
            "Basic achievement system",
            "100 karma earning cap/day",
            "Standard conversion rate (10 MA = 1 Karma)",
            "Basic mining pools (3 pools)",
            "Standard difficulty levels",
            "Basic leaderboard access",
            "Community project listing",
            "Basic hype popups",
            "Standard combo display",
            "Basic rank tracking",
            "Standard time boost tiers",
            "Basic anti-cheat protection",
            "Standard HMAC data security",
            "Basic rate limiting",
            "Standard proof-of-work mining",
            "Basic behavior analysis",
            "Standard anomaly detection",
            "Basic session tracking",
            "Standard replay prevention",
            "Basic memory integrity checks",
            "Standard cooldown enforcement",
            "Basic velocity monitoring",
            "Standard collusion detection",
            "Basic self-healing data",
            "Standard machine binding",
            "Basic tamper logging",
            "Standard violation tracking",
            "Basic export (JSON)",
            "Standard data retention (30 days)",
            "Basic analytics dashboard",
            "Standard notification system",
            "Community project contributions",
            "Basic concept analysis",
            "Standard hype comment display",
            "Basic rank progression",
            "Standard combo multiplier (max x1)",
            "Basic earning limits",
            "Standard staking (12% APY)",
        ],
    },
    "starter": {
        "name": "Starter",
        "price_monthly": 9.99,
        "price_lifetime": 299,
        "color": "bright_cyan",
        "icon": ">>",
        "badge": "STARTER",
        "features": [
            "Access to 25 AI models",
            "Advanced karma scoring",
            "Enhanced leaderboard",
            "20 mining sessions/day",
            "Fast response speed",
            "Advanced combo tracking",
            "All public project access",
            "Enhanced impact visualization",
            "10 color themes",
            "Extended transaction history (30 days)",
            "Priority community support",
            "Enhanced status dashboard",
            "Advanced karma profile",
            "Extended achievement system (50 achievements)",
            "500 karma earning cap/day",
            "Enhanced conversion rate (12 MA = 1 Karma)",
            "Extended mining pools (5 pools)",
            "Advanced difficulty levels",
            "Enhanced leaderboard access",
            "Featured project listing",
            "Enhanced hype popups",
            "Advanced combo display",
            "Enhanced rank tracking",
            "Extended time boost tiers",
            "Enhanced anti-cheat protection",
            "Advanced HMAC security",
            "Enhanced rate limiting",
            "Advanced proof-of-work",
            "Enhanced behavior analysis",
            "Advanced anomaly detection",
            "Enhanced session tracking",
            "Advanced replay prevention",
            "Enhanced memory integrity",
            "Advanced cooldown enforcement",
            "Enhanced velocity monitoring",
            "Advanced collusion detection",
            "Enhanced self-healing data",
            "Advanced machine binding",
            "Enhanced tamper logging",
            "Advanced violation tracking",
            "Enhanced export (JSON, CSV)",
            "Extended data retention (90 days)",
            "Enhanced analytics dashboard",
            "Advanced notification system",
            "Featured project contributions",
            "Enhanced concept analysis",
            "Advanced hype comment display",
            "Enhanced rank progression",
            "Advanced combo multiplier (max x1.5)",
            "Enhanced earning limits",
            "Advanced staking (14% APY)",
            "Personal impact statistics",
            "Weekly progress reports",
            "Custom notification preferences",
            "Advanced mining statistics",
            "Pool performance analytics",
            "Combo streak predictions",
            "Rank milestone tracking",
            "Impact score trends",
            "Earning optimization tips",
            "Community engagement metrics",
            "Project contribution history",
            "Karma growth charts",
            "Streak reliability analysis",
            "Mining efficiency reports",
            "Transaction categorization",
            "Budget tracking for MA tokens",
            "Goal setting for karma targets",
            "Milestone celebration popups",
            "Personal achievement gallery",
            "Impact portfolio overview",
            "Community reputation score",
            "Project recommendation engine",
            "Smart combo timing alerts",
            "Rank-up preparation guide",
            "Earning potential calculator",
            "Streak protection warnings",
            "Mining pool optimization",
            "Difficulty auto-adjustment",
            "Performance benchmarking",
            "Historical trend analysis",
            "Pattern recognition alerts",
            "Anomaly detection notifications",
            "Suspicious activity warnings",
            "Account security alerts",
            "Login activity monitoring",
            "Device management",
            "Session history viewing",
            "Active session tracking",
            "Permission management",
            "Data access controls",
            "Privacy settings",
            "Communication preferences",
            "Theme customization",
            "Layout personalization",
            "Dashboard widget configuration",
            "Quick action shortcuts",
            "Keyboard shortcuts",
            "Search functionality",
            "Filter and sort options",
            "Bulk action support",
            "Import/export tools",
            "Backup and restore",
            "Data migration tools",
            "API access (limited)",
            "Webhook support (basic)",
            "Integration marketplace",
            "Third-party app connections",
            "OAuth authentication",
            "Two-factor authentication",
            "Advanced encryption",
            "IP whitelisting",
            "Access log viewing",
            "Audit trail access",
            "Compliance reporting",
            "Data retention policies",
            "GDPR compliance tools",
            "CCPA compliance tools",
            "SOC 2 readiness",
            "ISO 27001 alignment",
            "NIST framework adherence",
            "Risk assessment tools",
            "Vulnerability scanning",
            "Penetration testing reports",
            "Security audit logs",
            "Incident response plan",
            "Business continuity plan",
            "Disaster recovery procedures",
            "SLA monitoring",
            "Uptime guarantees (99.5%)",
            "Performance SLAs",
            "Support response time SLAs",
            "Escalation procedures",
            "Account management",
            "Quarterly business reviews",
            "Strategic planning sessions",
            "ROI analysis tools",
            "Cost optimization reports",
            "Resource utilization metrics",
            "Capacity planning tools",
            "Scalability assessments",
            "Performance tuning guides",
            "Best practices documentation",
            "Training materials",
            "Certification programs",
            "Community forums",
            "Knowledge base access",
            "Video tutorials",
            "Webinar participation",
            "Conference discounts",
            "Networking opportunities",
            "Mentorship programs",
            "Career development resources",
            "Industry insights",
            "Market research reports",
            "Competitive analysis",
            "Trend forecasting",
            "Innovation tracking",
            "Patent monitoring",
            "Technology radar",
            "Digital transformation guides",
            "Agile methodology support",
            "DevOps best practices",
            "CI/CD pipeline tools",
            "Monitoring and alerting",
            "Log management",
            "Performance monitoring",
            "Error tracking",
            "Debugging tools",
            "Profiling utilities",
            "Load testing tools",
            "Stress testing capabilities",
            "Security scanning",
            "Code quality analysis",
            "Technical debt tracking",
            "Architecture documentation",
            "API documentation",
            "SDK and libraries",
            "Code samples",
            "Template gallery",
            "Plugin ecosystem",
            "Extension marketplace",
            "Custom integrations",
            "Workflow automation",
            "Task scheduling",
            "Batch processing",
            "Queue management",
            "Event-driven architecture",
            "Microservices support",
            "Container orchestration",
            "Cloud deployment tools",
            "Multi-cloud support",
            "Edge computing capabilities",
            "CDN integration",
            "Load balancing",
            "Auto-scaling",
            "Health monitoring",
            "Circuit breaker patterns",
            "Retry logic",
            "Fallback mechanisms",
            "Graceful degradation",
            "Feature flags",
            "A/B testing framework",
            "Canary deployments",
            "Blue-green deployments",
            "Rolling updates",
            "Hotfix capabilities",
            "Version control",
            "Branch management",
            "Code review tools",
            "Merge conflict resolution",
            "Release management",
            "Changelog generation",
            "Release notes automation",
            "Dependency management",
            "License compliance",
            "Security patching",
            "Vulnerability management",
            "Incident tracking",
            "Post-mortem analysis",
            "Root cause analysis",
            "Continuous improvement",
            "Process optimization",
            "Quality assurance",
            "Testing automation",
            "Test coverage reports",
            "Performance benchmarks",
            "Load testing results",
            "Security audit results",
            "Compliance certifications",
            "Industry standards adherence",
            "Regulatory compliance",
            "Data governance",
            "Information security",
            "Privacy protection",
            "Risk management",
            "Business continuity",
            "Disaster recovery",
            "Incident response",
            "Crisis management",
            "Stakeholder communication",
            "Change management",
            "Project management",
            "Resource planning",
            "Budget management",
            "Cost tracking",
            "ROI measurement",
            "Performance metrics",
            "KPI dashboards",
            "Reporting tools",
            "Analytics engine",
            "Data visualization",
            "Insight generation",
            "Predictive analytics",
            "Machine learning models",
            "AI-powered insights",
            "Automated recommendations",
            "Smart suggestions",
            "Intelligent automation",
            "Workflow optimization",
            "Process improvement",
            "Efficiency gains",
            "Productivity metrics",
            "Time tracking",
            "Resource allocation",
            "Capacity planning",
            "Demand forecasting",
            "Supply chain optimization",
            "Inventory management",
            "Order processing",
            "Payment processing",
            "Billing automation",
            "Invoice management",
            "Revenue recognition",
            "Financial reporting",
            "Tax compliance",
            "Audit preparation",
            "Regulatory reporting",
            "Governance framework",
            "Policy management",
            "Procedure documentation",
            "Training programs",
            "Certification paths",
            "Skill development",
            "Knowledge management",
            "Information sharing",
            "Collaboration tools",
            "Communication platforms",
            "Meeting management",
            "Project coordination",
            "Task delegation",
            "Progress tracking",
            "Milestone management",
            "Deliverable tracking",
            "Quality control",
            "Risk mitigation",
            "Issue resolution",
            "Conflict management",
            "Stakeholder engagement",
            "Relationship building",
            "Partnership development",
            "Alliance management",
            "Vendor management",
            "Contract management",
            "Service level agreements",
            "Performance monitoring",
            "Continuous improvement",
            "Innovation management",
            "Technology adoption",
            "Digital transformation",
            "Strategic planning",
            "Business development",
            "Market expansion",
            "Growth strategies",
            "Competitive positioning",
            "Brand management",
            "Reputation management",
            "Crisis communication",
            "Public relations",
            "Marketing automation",
            "Customer engagement",
            "User experience",
            "Service design",
            "Product development",
            "Agile delivery",
            "DevOps practices",
            "Cloud operations",
            "Security operations",
            "Compliance operations",
            "Governance operations",
            "Risk operations",
            "Quality operations",
            "Performance operations",
            "Capacity operations",
            "Availability operations",
            "Reliability operations",
            "Scalability operations",
            "Flexibility operations",
            "Agility operations",
            "Resilience operations",
            "Recovery operations",
            "Continuity operations",
            "Sustainability operations",
            "Environmental operations",
            "Social operations",
            "Governance ESG operations",
            "Ethics operations",
            "Transparency operations",
            "Accountability operations",
            "Compliance ESG operations",
            "Reporting ESG operations",
            "Monitoring ESG operations",
            "Auditing ESG operations",
            "Certification ESG operations",
            "Assessment ESG operations",
            "Improvement ESG operations",
            "Innovation ESG operations",
            "Collaboration ESG operations",
            "Engagement ESG operations",
            "Communication ESG operations",
            "Education ESG operations",
            "Training ESG operations",
            "Awareness ESG operations",
            "Advocacy ESG operations",
            "Leadership ESG operations",
            "Stewardship ESG operations",
        ],
    },
    "pro": {
        "name": "Pro",
        "price_monthly": 29.99,
        "price_lifetime": 799,
        "color": "bright_yellow",
        "icon": "**",
        "badge": "PRO",
        "features": [
            "Access to ALL 56 AI models",
            "Premium karma scoring",
            "Premium leaderboard",
            "Unlimited mining sessions",
            "Ultra-fast response speed",
            "Premium combo tracking",
            "All projects + featured placement",
            "Premium impact visualization",
            "25 color themes",
            "Full transaction history",
            "Priority email support",
            "Premium status dashboard",
            "Premium karma profile",
            "Full achievement system (100 achievements)",
            "2000 karma earning cap/day",
            "Premium conversion rate (15 MA = 1 Karma)",
            "All mining pools (6 pools)",
            "All difficulty levels",
            "Premium leaderboard access",
            "Top project placement",
            "Premium hype popups",
            "Premium combo display",
            "Premium rank tracking",
            "All time boost tiers",
            "Premium anti-cheat protection",
            "Premium HMAC security",
            "Premium rate limiting",
            "Premium proof-of-work",
            "Premium behavior analysis",
            "Premium anomaly detection",
            "Premium session tracking",
            "Premium replay prevention",
            "Premium memory integrity",
            "Premium cooldown enforcement",
            "Premium velocity monitoring",
            "Premium collusion detection",
            "Premium self-healing data",
            "Premium machine binding",
            "Premium tamper logging",
            "Premium violation tracking",
            "Premium export (JSON, CSV, PDF)",
            "Full data retention (1 year)",
            "Premium analytics dashboard",
            "Premium notification system",
            "Priority project contributions",
            "Premium concept analysis",
            "Premium hype comment display",
            "Premium rank progression",
            "Premium combo multiplier (max x3)",
            "Premium earning limits",
            "Premium staking (16% APY)",
            "Advanced personal statistics",
            "Daily progress reports",
            "Custom notification preferences",
            "Advanced mining statistics",
            "Pool performance analytics",
            "Combo streak predictions",
            "Rank milestone tracking",
            "Impact score trends",
            "Earning optimization tips",
            "Community engagement metrics",
            "Project contribution history",
            "Karma growth charts",
            "Streak reliability analysis",
            "Mining efficiency reports",
            "Transaction categorization",
            "Budget tracking for MA tokens",
            "Goal setting for karma targets",
            "Milestone celebration popups",
            "Personal achievement gallery",
            "Impact portfolio overview",
            "Community reputation score",
            "Project recommendation engine",
            "Smart combo timing alerts",
            "Rank-up preparation guide",
            "Earning potential calculator",
            "Streak protection warnings",
            "Mining pool optimization",
            "Difficulty auto-adjustment",
            "Performance benchmarking",
            "Historical trend analysis",
            "Pattern recognition alerts",
            "Anomaly detection notifications",
            "Suspicious activity warnings",
            "Account security alerts",
            "Login activity monitoring",
            "Device management",
            "Session history viewing",
            "Active session tracking",
            "Permission management",
            "Data access controls",
            "Privacy settings",
            "Communication preferences",
            "Theme customization",
            "Layout personalization",
            "Dashboard widget configuration",
            "Quick action shortcuts",
            "Keyboard shortcuts",
            "Advanced search functionality",
            "Advanced filter and sort",
            "Bulk action support",
            "Advanced import/export tools",
            "Backup and restore",
            "Data migration tools",
            "Full API access",
            "Full webhook support",
            "Integration marketplace",
            "Third-party app connections",
            "OAuth authentication",
            "Two-factor authentication",
            "Advanced encryption",
            "IP whitelisting",
            "Full access log viewing",
            "Full audit trail access",
            "Compliance reporting",
            "Data retention policies",
            "GDPR compliance tools",
            "CCPA compliance tools",
            "SOC 2 readiness",
            "ISO 27001 alignment",
            "NIST framework adherence",
            "Risk assessment tools",
            "Vulnerability scanning",
            "Penetration testing reports",
            "Security audit logs",
            "Incident response plan",
            "Business continuity plan",
            "Disaster recovery procedures",
            "SLA monitoring",
            "Uptime guarantees (99.9%)",
            "Performance SLAs",
            "Support response time SLAs",
            "Escalation procedures",
            "Dedicated account manager",
            "Monthly business reviews",
            "Strategic planning sessions",
            "ROI analysis tools",
            "Cost optimization reports",
            "Resource utilization metrics",
            "Capacity planning tools",
            "Scalability assessments",
            "Performance tuning guides",
            "Best practices documentation",
            "Premium training materials",
            "Certification programs",
            "Premium community forums",
            "Full knowledge base access",
            "Video tutorials",
            "Webinar participation",
            "Conference discounts",
            "Networking opportunities",
            "Mentorship programs",
            "Career development resources",
            "Industry insights",
            "Market research reports",
            "Competitive analysis",
            "Trend forecasting",
            "Innovation tracking",
            "Patent monitoring",
            "Technology radar",
            "Digital transformation guides",
            "Agile methodology support",
            "DevOps best practices",
            "CI/CD pipeline tools",
            "Monitoring and alerting",
            "Log management",
            "Performance monitoring",
            "Error tracking",
            "Debugging tools",
            "Profiling utilities",
            "Load testing tools",
            "Stress testing capabilities",
            "Security scanning",
            "Code quality analysis",
            "Technical debt tracking",
            "Architecture documentation",
            "API documentation",
            "SDK and libraries",
            "Code samples",
            "Template gallery",
            "Plugin ecosystem",
            "Extension marketplace",
            "Custom integrations",
            "Workflow automation",
            "Task scheduling",
            "Batch processing",
            "Queue management",
            "Event-driven architecture",
            "Microservices support",
            "Container orchestration",
            "Cloud deployment tools",
            "Multi-cloud support",
            "Edge computing capabilities",
            "CDN integration",
            "Load balancing",
            "Auto-scaling",
            "Health monitoring",
            "Circuit breaker patterns",
            "Retry logic",
            "Fallback mechanisms",
            "Graceful degradation",
            "Feature flags",
            "A/B testing framework",
            "Canary deployments",
            "Blue-green deployments",
            "Rolling updates",
            "Hotfix capabilities",
            "Version control",
            "Branch management",
            "Code review tools",
            "Merge conflict resolution",
            "Release management",
            "Changelog generation",
            "Release notes automation",
            "Dependency management",
            "License compliance",
            "Security patching",
            "Vulnerability management",
            "Incident tracking",
            "Post-mortem analysis",
            "Root cause analysis",
            "Continuous improvement",
            "Process optimization",
            "Quality assurance",
            "Testing automation",
            "Test coverage reports",
            "Performance benchmarks",
            "Load testing results",
            "Security audit results",
            "Compliance certifications",
            "Industry standards adherence",
            "Regulatory compliance",
            "Data governance",
            "Information security",
            "Privacy protection",
            "Risk management",
            "Business continuity",
            "Disaster recovery",
            "Incident response",
            "Crisis management",
            "Stakeholder communication",
            "Change management",
            "Project management",
            "Resource planning",
            "Budget management",
            "Cost tracking",
            "ROI measurement",
            "Performance metrics",
            "KPI dashboards",
            "Reporting tools",
            "Analytics engine",
            "Data visualization",
            "Insight generation",
            "Predictive analytics",
            "Machine learning models",
            "AI-powered insights",
            "Automated recommendations",
            "Smart suggestions",
            "Intelligent automation",
            "Workflow optimization",
            "Process improvement",
            "Efficiency gains",
            "Productivity metrics",
            "Time tracking",
            "Resource allocation",
            "Capacity planning",
            "Demand forecasting",
            "Supply chain optimization",
            "Inventory management",
            "Order processing",
            "Payment processing",
            "Billing automation",
            "Invoice management",
            "Revenue recognition",
            "Financial reporting",
            "Tax compliance",
            "Audit preparation",
            "Regulatory reporting",
            "Governance framework",
            "Policy management",
            "Procedure documentation",
            "Training programs",
            "Certification paths",
            "Skill development",
            "Knowledge management",
            "Information sharing",
            "Collaboration tools",
            "Communication platforms",
            "Meeting management",
            "Project coordination",
            "Task delegation",
            "Progress tracking",
            "Milestone management",
            "Deliverable tracking",
            "Quality control",
            "Risk mitigation",
            "Issue resolution",
            "Conflict management",
            "Stakeholder engagement",
            "Relationship building",
            "Partnership development",
            "Alliance management",
            "Vendor management",
            "Contract management",
            "Service level agreements",
            "Performance monitoring",
            "Continuous improvement",
            "Innovation management",
            "Technology adoption",
            "Digital transformation",
            "Strategic planning",
            "Business development",
            "Market expansion",
            "Growth strategies",
            "Competitive positioning",
            "Brand management",
            "Reputation management",
            "Crisis communication",
            "Public relations",
            "Marketing automation",
            "Customer engagement",
            "User experience",
            "Service design",
            "Product development",
            "Agile delivery",
            "DevOps practices",
            "Cloud operations",
            "Security operations",
            "Compliance operations",
            "Governance operations",
            "Risk operations",
            "Quality operations",
            "Performance operations",
            "Capacity operations",
            "Availability operations",
            "Reliability operations",
            "Scalability operations",
            "Flexibility operations",
            "Agility operations",
            "Resilience operations",
            "Recovery operations",
            "Continuity operations",
            "Sustainability operations",
            "Environmental operations",
            "Social operations",
            "Governance ESG operations",
            "Ethics operations",
            "Transparency operations",
            "Accountability operations",
            "Compliance ESG operations",
            "Reporting ESG operations",
            "Monitoring ESG operations",
            "Auditing ESG operations",
            "Certification ESG operations",
            "Assessment ESG operations",
            "Improvement ESG operations",
            "Innovation ESG operations",
            "Collaboration ESG operations",
            "Engagement ESG operations",
            "Communication ESG operations",
            "Education ESG operations",
            "Training ESG operations",
            "Awareness ESG operations",
            "Advocacy ESG operations",
            "Leadership ESG operations",
            "Stewardship ESG operations",
        ],
    },
    "ultimate": {
        "name": "Ultimate",
        "price_monthly": 99.99,
        "price_lifetime": 1999,
        "color": "bright_magenta",
        "icon": "**+",
        "badge": "ULTIMATE",
        "features": [
            "ALL Pro features included",
            "Priority model access (no queuing)",
            "Custom model fine-tuning",
            "Advanced API rate limits (10x)",
            "Real-time analytics dashboard",
            "Predictive impact modeling",
            "AI-powered optimization",
            "Custom mining algorithms",
            "Priority mining pool access",
            "Advanced combo strategies",
            "Exclusive rank-up bonuses",
            "Custom achievement creation",
            "White-label reports",
            "Advanced data export (all formats)",
            "Unlimited data retention",
            "Priority support (1hr response)",
            "Dedicated account manager",
            "Custom integrations",
            "Advanced API webhooks",
            "Custom notification rules",
            "Advanced security features",
            "Custom encryption keys",
            "Advanced audit logging",
            "Custom compliance rules",
            "Advanced SLA (99.99% uptime)",
            "Custom training programs",
            "Advanced analytics (ML-powered)",
            "Custom reporting dashboards",
            "Advanced automation (AI-driven)",
            "Custom workflow engine",
            "Advanced collaboration tools",
            "Custom project templates",
            "Advanced resource optimization",
            "Custom capacity planning",
            "Advanced performance tuning",
            "Custom architecture design",
            "Advanced security scanning",
            "Custom incident response",
            "Advanced disaster recovery",
            "Custom business continuity",
            "Advanced risk management",
            "Custom governance framework",
            "Advanced compliance automation",
            "Custom data governance",
            "Advanced privacy protection",
            "Custom audit preparation",
            "Advanced regulatory reporting",
            "Custom financial reporting",
            "Advanced tax optimization",
            "Custom revenue recognition",
            "Advanced billing automation",
            "Custom payment processing",
            "Advanced order management",
            "Custom inventory optimization",
            "Advanced supply chain management",
            "Custom demand forecasting",
            "Advanced capacity optimization",
            "Custom resource allocation",
            "Advanced time optimization",
            "Custom productivity analytics",
            "Advanced efficiency optimization",
            "Custom process improvement",
            "Advanced workflow optimization",
            "Custom automation engine",
            "Advanced AI-powered insights",
            "Custom machine learning models",
            "Advanced predictive analytics",
            "Custom data visualization",
            "Advanced trend analysis",
            "Custom pattern recognition",
            "Advanced anomaly detection",
            "Custom behavior analysis",
            "Advanced threat detection",
            "Custom security intelligence",
            "Advanced vulnerability management",
            "Custom penetration testing",
            "Advanced security auditing",
            "Custom compliance monitoring",
            "Advanced risk assessment",
            "Custom incident management",
            "Advanced post-mortem analysis",
            "Custom root cause analysis",
            "Advanced continuous improvement",
            "Custom quality assurance",
            "Advanced testing automation",
            "Custom test management",
            "Advanced performance benchmarking",
            "Custom load testing",
            "Advanced stress testing",
            "Custom security testing",
            "Advanced code quality analysis",
            "Custom technical debt tracking",
            "Advanced architecture documentation",
            "Custom API documentation",
            "Advanced SDK management",
            "Custom code samples",
            "Advanced template management",
            "Custom plugin development",
            "Advanced extension management",
            "Custom integration development",
            "Advanced workflow design",
            "Custom task automation",
            "Advanced batch processing",
            "Custom queue management",
            "Advanced event architecture",
            "Custom microservices design",
            "Advanced container management",
            "Custom cloud architecture",
            "Advanced multi-cloud management",
            "Custom edge computing",
            "Advanced CDN optimization",
            "Custom load balancing",
            "Advanced auto-scaling",
            "Custom health monitoring",
            "Advanced circuit breaker design",
            "Custom retry strategies",
            "Advanced fallback mechanisms",
            "Custom graceful degradation",
            "Advanced feature flag management",
            "Custom A/B testing",
            "Advanced canary deployment",
            "Custom blue-green deployment",
            "Advanced rolling update management",
            "Custom hotfix procedures",
            "Advanced version control",
            "Custom branch strategies",
            "Advanced code review processes",
            "Custom merge strategies",
            "Advanced release management",
            "Custom changelog generation",
            "Advanced release note automation",
            "Custom dependency management",
            "Advanced license compliance",
            "Custom security patching",
            "Advanced vulnerability tracking",
            "Custom incident tracking",
            "Advanced post-mortem processes",
            "Custom root cause investigation",
            "Advanced continuous improvement",
            "Custom process optimization",
            "Advanced quality assurance",
            "Custom testing frameworks",
            "Advanced test automation",
            "Custom performance monitoring",
            "Advanced load testing tools",
            "Custom stress testing tools",
            "Advanced security scanning tools",
            "Custom code analysis tools",
            "Advanced technical debt tools",
            "Custom architecture tools",
            "Advanced API management tools",
            "Custom SDK tools",
            "Advanced code generation tools",
            "Custom template engines",
            "Advanced plugin frameworks",
            "Custom extension systems",
            "Advanced integration platforms",
            "Custom workflow platforms",
            "Advanced task automation platforms",
            "Custom batch processing platforms",
            "Advanced queue platforms",
            "Custom event platforms",
            "Advanced microservices platforms",
            "Custom container platforms",
            "Advanced cloud platforms",
            "Custom multi-cloud platforms",
            "Advanced edge platforms",
            "Custom CDN platforms",
            "Advanced load balancing platforms",
            "Custom auto-scaling platforms",
            "Advanced monitoring platforms",
            "Custom alerting platforms",
            "Advanced logging platforms",
            "Custom debugging platforms",
            "Advanced profiling platforms",
            "Custom testing platforms",
            "Advanced security platforms",
            "Custom compliance platforms",
            "Advanced governance platforms",
            "Custom risk platforms",
            "Advanced quality platforms",
            "Custom performance platforms",
            "Advanced capacity platforms",
            "Custom availability platforms",
            "Advanced reliability platforms",
            "Custom scalability platforms",
            "Advanced flexibility platforms",
            "Custom agility platforms",
            "Advanced resilience platforms",
            "Custom recovery platforms",
            "Advanced continuity platforms",
            "Custom sustainability platforms",
            "Advanced environmental platforms",
            "Custom social platforms",
            "Advanced ESG platforms",
            "Custom ethics platforms",
            "Advanced transparency platforms",
            "Custom accountability platforms",
            "Advanced compliance ESG platforms",
            "Custom reporting ESG platforms",
            "Advanced monitoring ESG platforms",
            "Custom auditing ESG platforms",
            "Advanced certification ESG platforms",
            "Custom assessment ESG platforms",
            "Advanced improvement ESG platforms",
            "Custom innovation ESG platforms",
            "Advanced collaboration ESG platforms",
            "Custom engagement ESG platforms",
            "Advanced communication ESG platforms",
            "Custom education ESG platforms",
            "Advanced training ESG platforms",
            "Custom awareness ESG platforms",
            "Advanced advocacy ESG platforms",
            "Custom leadership ESG platforms",
            "Advanced stewardship ESG platforms",
        ],
    },
    "enterprise": {
        "name": "Enterprise",
        "price_monthly": 299.99,
        "price_lifetime": 4999,
        "color": "bright_red",
        "icon": "##+",
        "badge": "ENTERPRISE",
        "features": [
            "ALL Ultimate features included",
            "White-label platform deployment",
            "Custom branding and themes",
            "Dedicated infrastructure",
            "Custom model deployment",
            "Enterprise API gateway",
            "Advanced security suite",
            "Custom compliance engine",
            "Dedicated support team",
            "Custom SLA agreements",
            "Enterprise analytics suite",
            "Custom data pipelines",
            "Advanced ML operations",
            "Custom AI model training",
            "Enterprise integration hub",
            "Custom workflow engine",
            "Advanced automation suite",
            "Custom deployment pipeline",
            "Enterprise monitoring suite",
            "Custom alerting rules",
            "Advanced incident management",
            "Custom post-mortem processes",
            "Enterprise security suite",
            "Custom threat detection",
            "Advanced vulnerability management",
            "Custom penetration testing",
            "Enterprise compliance suite",
            "Custom audit management",
            "Advanced regulatory reporting",
            "Custom financial reporting",
            "Enterprise governance suite",
            "Custom policy management",
            "Advanced procedure automation",
            "Custom training platform",
            "Enterprise knowledge base",
            "Custom documentation system",
            "Advanced API management",
            "Custom integration framework",
            "Enterprise collaboration suite",
            "Custom project management",
            "Advanced resource planning",
            "Custom capacity management",
            "Enterprise performance suite",
            "Custom optimization engine",
            "Advanced benchmarking platform",
            "Custom load testing suite",
            "Enterprise security scanning",
            "Custom code analysis platform",
            "Advanced technical debt management",
            "Custom architecture platform",
            "Enterprise API gateway",
            "Custom SDK platform",
            "Advanced code generation",
            "Custom template platform",
            "Enterprise plugin ecosystem",
            "Custom extension framework",
            "Advanced integration marketplace",
            "Custom workflow platform",
            "Enterprise task automation",
            "Custom batch processing platform",
            "Advanced queue management",
            "Custom event architecture",
            "Enterprise microservices platform",
            "Custom container orchestration",
            "Advanced cloud management",
            "Custom multi-cloud platform",
            "Enterprise edge computing",
            "Custom CDN platform",
            "Advanced load balancing",
            "Custom auto-scaling platform",
            "Enterprise monitoring platform",
            "Custom alerting platform",
            "Advanced logging platform",
            "Custom debugging platform",
            "Enterprise profiling platform",
            "Custom testing platform",
            "Advanced security platform",
            "Custom compliance platform",
            "Enterprise governance platform",
            "Custom risk platform",
            "Advanced quality platform",
            "Custom performance platform",
            "Enterprise capacity platform",
            "Custom availability platform",
            "Advanced reliability platform",
            "Custom scalability platform",
            "Enterprise flexibility platform",
            "Custom agility platform",
            "Advanced resilience platform",
            "Custom recovery platform",
            "Enterprise continuity platform",
            "Custom sustainability platform",
            "Advanced environmental platform",
            "Custom social platform",
            "Enterprise ESG platform",
            "Custom ethics platform",
            "Advanced transparency platform",
            "Custom accountability platform",
            "Enterprise compliance ESG platform",
            "Custom reporting ESG platform",
            "Advanced monitoring ESG platform",
            "Custom auditing ESG platform",
            "Enterprise certification ESG platform",
            "Custom assessment ESG platform",
            "Advanced improvement ESG platform",
            "Custom innovation ESG platform",
            "Enterprise collaboration ESG platform",
            "Custom engagement ESG platform",
            "Advanced communication ESG platform",
            "Custom education ESG platform",
            "Enterprise training ESG platform",
            "Custom awareness ESG platform",
            "Advanced advocacy ESG platform",
            "Custom leadership ESG platform",
            "Enterprise stewardship ESG platform",
        ],
    },
}

PLAN_ORDER = ["free", "starter", "pro", "ultimate", "enterprise"]


def _load_sub():
    if os.path.exists(SUB_FILE):
        with open(SUB_FILE, "r") as f:
            return json.load(f)
    return {"users": {}, "transactions": []}


def _save_sub(data):
    with open(SUB_FILE, "w") as f:
        json.dump(data, f, indent=2)


PLAN_MODEL_ACCESS = {
    "free":       ["flash"],
    "starter":    ["flash", "lite", "pro"],
    "pro":        ["flash", "lite", "pro", "expert", "senior"],
    "ultimate":   ["flash", "lite", "pro", "expert", "senior", "pro-max", "expert-ultra", "senior-elite"],
    "enterprise": ["flash", "lite", "pro", "expert", "senior", "pro-max", "expert-ultra", "senior-elite"],
}


class SubscriptionEngine:
    """Manages user subscriptions, upgrades, and lifetime purchases."""

    def __init__(self):
        self.data = _load_sub()

    def get_user_plan(self, user_id="default"):
        if user_id not in self.data["users"]:
            self.data["users"][user_id] = {
                "plan": "free",
                "is_lifetime": False,
                "subscribed_at": None,
                "expires_at": None,
                "upgrades": [],
                "total_spent": 0.0,
            }
            _save_sub(self.data)
        return self.data["users"][user_id]

    def subscribe(self, user_id, plan, is_lifetime=False):
        if plan not in PLAN_FEATURES or plan == "free":
            return {"error": "Invalid plan"}
        user = self.get_user_plan(user_id)
        plan_info = PLAN_FEATURES[plan]
        price = plan_info["price_lifetime"] if is_lifetime else plan_info["price_monthly"]

        prev_plan = user["plan"]
        user["plan"] = plan
        user["is_lifetime"] = is_lifetime
        user["subscribed_at"] = datetime.utcnow().isoformat()
        if not is_lifetime:
            from datetime import timedelta
            user["expires_at"] = (datetime.utcnow() + timedelta(days=30)).isoformat()
        else:
            user["expires_at"] = None
        user["total_spent"] = round(user["total_spent"] + price, 2)
        user["upgrades"].append({
            "from": prev_plan, "to": plan,
            "lifetime": is_lifetime,
            "price": price,
            "time": datetime.utcnow().isoformat(),
        })

        self.data["transactions"].append({
            "user_id": user_id,
            "type": "lifetime_purchase" if is_lifetime else "monthly_subscription",
            "plan": plan,
            "amount": price,
            "time": datetime.utcnow().isoformat(),
        })
        _save_sub(self.data)

        return {
            "plan": plan,
            "plan_name": plan_info["name"],
            "lifetime": is_lifetime,
            "price": price,
            "features_count": len(plan_info["features"]),
            "color": plan_info["color"],
            "badge": plan_info["badge"],
            "icon": plan_info["icon"],
        }

    def upgrade(self, user_id):
        user = self.get_user_plan(user_id)
        current = user["plan"]
        idx = PLAN_ORDER.index(current) if current in PLAN_ORDER else 0
        if idx < len(PLAN_ORDER) - 1:
            next_plan = PLAN_ORDER[idx + 1]
            return self.subscribe(user_id, next_plan, is_lifetime=user["is_lifetime"])
        return {"error": "Already at highest plan"}

    def get_plan_features(self, plan):
        if plan in PLAN_FEATURES:
            return PLAN_FEATURES[plan]
        return PLAN_FEATURES["free"]

    def get_all_plans(self):
        return PLAN_FEATURES

    def get_plan_comparison(self):
        comparison = []
        for plan_id in PLAN_ORDER:
            plan = PLAN_FEATURES[plan_id]
            comparison.append({
                "id": plan_id,
                "name": plan["name"],
                "price": plan["price_monthly"],
                "lifetime": plan["price_lifetime"],
                "features_count": len(plan["features"]),
                "color": plan["color"],
                "icon": plan["icon"],
                "badge": plan["badge"],
            })
        return comparison

    def get_user_transactions(self, user_id, limit=20):
        txs = [t for t in self.data["transactions"] if t.get("user_id") == user_id]
        return txs[-limit:]

    def has_feature(self, user_id, feature_name):
        user = self.get_user_plan(user_id)
        plan = user["plan"]
        features = PLAN_FEATURES.get(plan, PLAN_FEATURES["free"])
        return feature_name in [f.lower() for f in features["features"]]

    def get_feature_count(self, plan):
        if plan in PLAN_FEATURES:
            return len(PLAN_FEATURES[plan]["features"])
        return 0

    def can_access_model(self, user_id, model_tier):
        """Check if user's plan allows access to the given model tier."""
        user = self.get_user_plan(user_id)
        plan = user["plan"]
        allowed_tiers = PLAN_MODEL_ACCESS.get(plan, ["flash"])
        return model_tier in allowed_tiers

    def get_allowed_tiers(self, user_id):
        """Return list of model tiers allowed for user."""
        user = self.get_user_plan(user_id)
        plan = user["plan"]
        return PLAN_MODEL_ACCESS.get(plan, ["flash"])
